#!/usr/bin/env python3
"""Build the worker and self-contained offline game from the published site sources."""
from pathlib import Path
import base64,re
ROOT=Path(__file__).resolve().parent
WORKER=['physics.js','rules.js','apa.js','execution.js','coach.js','worker.js']
SCRIPTS=['physics.js','rules.js','settings.js','execution.js','apa.js','session.js','placement.js','renderer3d.js','worker-bundle.js','app.js']
def build():
    worker='\n'.join((ROOT/'src'/f).read_text(encoding='utf8') for f in WORKER)
    blob=base64.b64encode(worker.encode()).decode()
    (ROOT/'src/worker-bundle.js').write_text('/* Generated by build.py. Edit source modules, not this file. */\nwindow.CueWorkerSource="'+blob+'";\n')
    html=(ROOT/'index.html').read_text()
    for name in ['style.css','features.css']:
        pattern=r'<link rel="stylesheet" href="src/'+re.escape(name)+r'(?:\?[^\"]*)?">'
        html,n=re.subn(pattern,lambda _: '<style>'+(ROOT/'src'/name).read_text()+'</style>',html)
        if n!=1: raise ValueError(f'Expected one stylesheet reference for {name}')
    for name in SCRIPTS:
        code=(ROOT/'src'/name).read_text().replace('</script','<\\/script')
        pattern=r'<script src="src/'+re.escape(name)+r'(?:\?[^\"]*)?"></script>'
        html,n=re.subn(pattern,lambda _:'<script>'+code+'</script>',html)
        if n!=1:raise ValueError(f'Expected one script reference for {name}')
    if re.search(r'\b(?:src|href)="(?:https?:|src/)',html):raise ValueError('Unexpected external asset in offline bundle')
    target=ROOT/'Cue-Lab.html';target.write_text(html,encoding='utf8');print(f'Built {target.name}: {target.stat().st_size:,} bytes');return target
if __name__=='__main__':build()
