'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../src/physics.js'),Placement=require('../src/placement.js');
const near=(a,b,tol=1e-10)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const setup=()=>new P.World([P.ball(0,.4,.5),P.ball(1,1,.5)]);
test('opening and changing a placement preview does not mutate any world state',()=>{const w=setup(),before=w.snapshot(),e=new Placement(w);e.layout(412,640);e.set(.3,.2,true);e.nudge(1,-1);e.setZoom(9);assert.deepEqual(w.snapshot(),before);});
test('default camera magnifies by six and keeps the candidate centered',()=>{const e=new Placement(setup());e.layout(412,640);near(e.zoom,6);near(e.screen()[0],206);near(e.screen()[1],320);});
test('default nudge is exactly one millimeter in world units',()=>{const e=new Placement(setup());e.nudge(1,-1);near(e.x,.401);near(e.y,.499);});
test('five and ten millimeter nudges do not depend on zoom',()=>{const e=new Placement(setup());e.setZoom(10);e.step=.005;e.nudge(-1,1);near(e.x,.395);near(e.y,.505);e.step=.01;e.nudge(1,-1);near(e.x,.405);near(e.y,.495);});
test('screen and table coordinates round-trip at every zoom level',()=>{const e=new Placement(setup());for(let z=2;z<=10;z++){e.layout(390,500);e.setZoom(z);const p=e.point(...e.screen(.312,.456));near(p[0],.312);near(p[1],.456);}});
test('zoom clamps to the available range',()=>{const e=new Placement(setup());e.setZoom(99);assert.equal(e.zoom,10);e.setZoom(-1);assert.equal(e.zoom,2);});
test('orientation and canvas resize preserve the chosen table position',()=>{const e=new Placement(setup());e.set(.35,.42,true);e.layout(915,412);e.layout(412,915);near(e.x,.35);near(e.y,.42);near(e.point(...e.screen())[0],.35);});
test('overlap is rejected without moving the original ball',()=>{const w=setup(),before=w.snapshot(),e=new Placement(w);e.set(1,.5);assert.equal(e.valid(),false);assert.match(e.reason(),/another ball/);assert.equal(e.commit(),false);assert.deepEqual(w.snapshot(),before);});
test('off-cloth and rail-overlapping previews cannot be confirmed',()=>{const e=new Placement(setup());for(const p of [[0,.5],[P.L,.5],[.4,0],[.4,P.W]]){e.set(...p);assert.equal(e.valid(),false);assert.match(e.reason(),/whole ball/);assert.equal(e.commit(),false);}});
test('kitchen restriction is enforced on the candidate and confirmation',()=>{const w=setup(),e=new Placement(w,0,true);e.set(.7,.6);assert.equal(e.valid(),false);assert.equal(e.commit(),false);assert.match(e.reason(),/kitchen/);e.set(P.L/4,.6);assert.equal(e.valid(),true);assert.equal(e.commit(),true);near(w.get(0).p[0],P.L/4);});
test('valid confirmation moves only the selected ball and stops its motion',()=>{const w=setup(),other=P.clone(w.get(1)),e=new Placement(w);e.set(.23,.48);assert.equal(e.commit(),true);assert.deepEqual(w.get(0).p,[.23,.48,P.R]);assert.deepEqual(w.get(0).v,[0,0,0]);assert.deepEqual(w.get(1),other);});
test('original spot reset is still only a preview',()=>{const w=setup(),before=w.snapshot(),e=new Placement(w);e.set(.3,.7,true);e.reset();near(e.x,.4);near(e.y,.5);assert.deepEqual(w.snapshot(),before);});
test('the selected ball is excluded from overlap checks',()=>{const e=new Placement(setup());e.nudge(1,0);assert.equal(e.valid(),true);});
test('a missing practice ball is only added when placement is confirmed',()=>{const w=setup(),e=new Placement(w,15);assert.equal(w.get(15),undefined);e.set(.8,.8);assert.equal(e.commit(),true);assert.deepEqual(w.get(15).p,[.8,.8,P.R]);});
test('invalid coordinate input leaves the candidate unchanged',()=>{const e=new Placement(setup());assert.equal(e.set(NaN,.3),false);assert.equal(e.set(.3,Infinity),false);near(e.x,.4);near(e.y,.5);});
