'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../src/physics.js'),Q=require('../src/rules.js');
const hit=(id,t=.1)=>({type:'ball',a:0,b:id,t});
const rail=(id=0,t=.2,kind='cushion')=>({type:'rail',id,t,kind,rail:0});
const pot=(id,pocket=2,t=.3)=>({type:'pocket',id,pocket,t});
function fixture(mode,ids=null){const r=new Q.Rules(mode),w=new P.World(ids?ids.map((id,i)=>P.ball(id,.8+i*.09,.5)):P.rack(mode));r.break=false;r.ballInHand=null;return {r,w};}
function shoot(r,w,events,opts={}){const pre=r.start(w,opts);w.events=events;for(const e of events)if(e.type==='pocket'||e.type==='off'){let b=w.get(e.id);if(b){b.active=false;b.pocket=e.pocket??-1;P.stop?.(b);}}r.finish(w,pre);return pre;}
test('8-ball: break pots do not choose groups',()=>{const {r,w}=fixture('8ball');r.break=true;shoot(r,w,[hit(1),pot(1)]);assert.deepEqual(r.groups,[null,null]);assert.equal(r.turn,0);});
test('8-ball: called legal pot chooses groups',()=>{const {r,w}=fixture('8ball');shoot(r,w,[hit(1),pot(1)],{callBall:1,callPocket:2});assert.deepEqual(r.groups,['solids','stripes']);assert.equal(r.turn,0);});
test('8-ball: uncalled pots do not choose groups',()=>{const {r,w}=fixture('8ball');shoot(r,w,[hit(1),pot(1)]);assert.deepEqual(r.groups,[null,null]);assert.equal(r.turn,1);});
test('8-ball: legal called 8 after clearing wins',()=>{const {r,w}=fixture('8ball',[0,8,9]);r.groups=['solids','stripes'];shoot(r,w,[hit(8),pot(8)],{callBall:8,callPocket:2});assert.equal(r.winner,0);});
test('8-ball: early 8 loses',()=>{const {r,w}=fixture('8ball');r.groups=['solids','stripes'];shoot(r,w,[hit(1),pot(8)],{callBall:8,callPocket:2});assert.equal(r.winner,1);});
test('8-ball: wrong-pocket 8 loses',()=>{const {r,w}=fixture('8ball',[0,8]);r.groups=['solids','stripes'];shoot(r,w,[hit(8),pot(8,1)],{callBall:8,callPocket:2});assert.equal(r.winner,1);});
test('8-ball: scratched 8 loses',()=>{const {r,w}=fixture('8ball',[0,8]);r.groups=['solids','stripes'];shoot(r,w,[hit(8),pot(8),pot(0)],{callBall:8,callPocket:2});assert.equal(r.winner,1);});
test('8-ball: break 8 is spotted, not a win',()=>{const {r,w}=fixture('8ball');r.break=true;shoot(r,w,[hit(1),pot(8)]);assert.equal(r.winner,null);assert.ok(w.get(8).active);});
test('8-ball: wrong first contact gives ball in hand',()=>{const {r,w}=fixture('8ball');r.groups=['solids','stripes'];shoot(r,w,[hit(9),rail()]);assert.equal(r.turn,1);assert.equal(r.ballInHand,'any');});
test('8-ball: dry legal break counts distinct object balls, not cue rails',()=>{const {r,w}=fixture('8ball');r.break=true;shoot(r,w,[hit(1),rail(1),rail(2),rail(3),rail(4)]);assert.equal(r.ballInHand,null);assert.equal(r.turn,1);});
test('8-ball: repeated rails by one object are not four break rails',()=>{const {r,w}=fixture('8ball');r.break=true;shoot(r,w,[hit(1),rail(1),rail(1),rail(1),rail(1)]);assert.equal(r.ballInHand,'kitchen');});
test('9-ball: legal combination on 9 wins',()=>{const {r,w}=fixture('9ball');shoot(r,w,[hit(1),pot(9)]);assert.equal(r.winner,0);});
test('9-ball: a fouled 9 is spotted',()=>{const {r,w}=fixture('9ball');shoot(r,w,[hit(2),pot(9)]);assert.equal(r.winner,null);assert.ok(w.get(9).active);assert.equal(r.ballInHand,'any');});
test('9-ball: legal break enables push-out',()=>{const {r,w}=fixture('9ball');r.break=true;shoot(r,w,[hit(1),pot(2)]);assert.ok(r.pushAvailable);});
test('9-ball: declared push-out waives first-ball and rail requirements',()=>{const {r,w}=fixture('9ball');r.pushAvailable=true;shoot(r,w,[],{push:true});assert.equal(r.fouls[0],0);assert.equal(r.choice.type,'push');assert.equal(r.turn,1);});
test('9-ball: returning a push-out returns the shooter',()=>{const {r,w}=fixture('9ball');r.pushAvailable=true;shoot(r,w,[],{push:true});r.choose(w,false);assert.equal(r.turn,0);assert.equal(r.choice,null);});
test('9-ball: accepting a push-out leaves incoming player at table',()=>{const {r,w}=fixture('9ball');r.pushAvailable=true;shoot(r,w,[],{push:true});r.choose(w,true);assert.equal(r.turn,1);});
test('9-ball: a push-out scratch is still a foul',()=>{const {r,w}=fixture('9ball');r.pushAvailable=true;shoot(r,w,[pot(0)],{push:true});assert.equal(r.choice,null);assert.equal(r.ballInHand,'any');});
test('9-ball: third consecutive foul loses',()=>{const {r,w}=fixture('9ball');r.fouls[0]=2;shoot(r,w,[]);assert.equal(r.winner,1);});
test('10-ball: early called 10 is spotted',()=>{const {r,w}=fixture('10ball');shoot(r,w,[hit(1),pot(10)],{callBall:10,callPocket:2});assert.equal(r.winner,null);assert.ok(w.get(10).active);});
test('10-ball: called last 10 wins',()=>{const {r,w}=fixture('10ball',[0,10]);shoot(r,w,[hit(10),pot(10)],{callBall:10,callPocket:2});assert.equal(r.winner,0);});
test('10-ball: uncalled pot creates take-or-return decision',()=>{const {r,w}=fixture('10ball');shoot(r,w,[hit(1),pot(1,3)],{callBall:1,callPocket:2});assert.equal(r.choice.type,'return');r.choose(w,false);assert.equal(r.turn,0);});
test('10-ball: a break-shot 10 does not win',()=>{const {r,w}=fixture('10ball');r.break=true;shoot(r,w,[hit(1),pot(10)]);assert.equal(r.winner,null);assert.ok(w.get(10).active);});
test('14.1: every ball on a legal called shot scores',()=>{const {r,w}=fixture('straight');shoot(r,w,[hit(1),pot(1),pot(2),pot(3)],{callBall:1,callPocket:2});assert.equal(r.scores[0],3);assert.equal(r.runs[0],3);assert.equal(r.high[0],3);});
test('14.1: uncalled balls are spotted with no score',()=>{const {r,w}=fixture('straight');shoot(r,w,[hit(1),pot(1)]);assert.equal(r.scores[0],0);assert.ok(w.get(1).active);assert.equal(r.turn,1);});
test('14.1: safety pots are spotted',()=>{const {r,w}=fixture('straight');shoot(r,w,[hit(1),pot(1)],{callBall:1,callPocket:2,safety:true});assert.equal(r.scores[0],0);assert.ok(w.get(1).active);});
test('14.1: ordinary foul deducts one; does not grant arbitrary ball in hand',()=>{const {r,w}=fixture('straight');shoot(r,w,[hit(1)]);assert.equal(r.scores[0],-1);assert.equal(r.ballInHand,null);});
test('14.1: scratch grants kitchen ball in hand',()=>{const {r,w}=fixture('straight');shoot(r,w,[hit(1),pot(0)]);assert.equal(r.scores[0],-1);assert.equal(r.ballInHand,'kitchen');assert.ok(w.get(0).active);});
test('14.1: third foul deducts sixteen on that shot and requires a new break',()=>{const {r,w}=fixture('straight');r.fouls[0]=2;shoot(r,w,[]);assert.equal(r.scores[0],-16);assert.equal(r.break,true);assert.equal(r.turn,0);assert.equal(Q.objects(w).length,15);});
test('14.1: breaking foul gives accept or rebreak choice',()=>{const {r,w}=fixture('straight');r.break=true;shoot(r,w,[hit(1),rail(0)],{safety:true});assert.equal(r.scores[0],-2);assert.equal(r.choice.type,'straightBreak');r.choose(w,false);assert.equal(r.turn,0);assert.equal(r.break,true);});
test('14.1: accepted breaking foul leaves table to incoming player',()=>{const {r,w}=fixture('straight');r.break=true;shoot(r,w,[hit(1)],{safety:true});r.choose(w,true);assert.equal(r.turn,1);assert.equal(r.break,false);});
test('14.1: normal fourteen-ball rerack preserves break ball and cue position',()=>{const {r,w}=fixture('straight');for(const b of w.balls)b.active=b.id===0||b.id===15;w.get(0).p=[.4,.4,P.R];w.get(15).p=[1.4,.7,P.R];const a=P.clone(w.get(0).p),b=P.clone(w.get(15).p);Q.rerackStraight(w);assert.equal(Q.objects(w).length,15);assert.deepEqual(w.get(0).p,a);assert.deepEqual(w.get(15).p,b);});
test('14.1: an interfering break ball moves to the head spot',()=>{const {r,w}=fixture('straight');for(const b of w.balls)b.active=b.id===0||b.id===15;w.get(0).p=[.4,.4,P.R];w.get(15).p=[2.0,P.W/2,P.R];Q.rerackStraight(w);assert.equal(w.get(15).p[0],P.L/4);});
test('14.1: a blocked head spot moves the break ball to the center',()=>{const {r,w}=fixture('straight');for(const b of w.balls)b.active=b.id===0||b.id===15;w.get(0).p=[P.L/4,P.W/2,P.R];w.get(15).p=[2,P.W/2,P.R];Q.rerackStraight(w);assert.equal(w.get(15).p[0],P.L/2);});
test('14.1: both balls interfering produces full rack and kitchen ball in hand',()=>{const {r,w}=fixture('straight');for(const b of w.balls)b.active=b.id===0||b.id===15;w.get(0).p=[2,.59,P.R];w.get(15).p=[2,.68,P.R];const result=Q.rerackStraight(w);assert.equal(result.hand,'kitchen');assert.equal(Q.objects(w).length,15);});
test('14.1: cue interference with break ball behind head string spots cue at head',()=>{const {r,w}=fixture('straight');for(const b of w.balls)b.active=b.id===0||b.id===15;w.get(0).p=[2,.59,P.R];w.get(15).p=[.3,.4,P.R];const result=Q.rerackStraight(w);assert.equal(result.hand,null);assert.equal(w.get(0).p[0],P.L/4);});
test('14.1: target score ends the match',()=>{const {r,w}=fixture('straight');r.target=2;r.scores[0]=1;shoot(r,w,[hit(1),pot(1)],{callBall:1,callPocket:2});assert.equal(r.winner,0);});
test('one-pocket: own pocket scores and keeps the inning',()=>{const {r,w}=fixture('onepocket');shoot(r,w,[hit(1),pot(1,2)]);assert.equal(r.scores[0],1);assert.equal(r.turn,0);});
test('one-pocket: opponent pocket scores for opponent',()=>{const {r,w}=fixture('onepocket');shoot(r,w,[hit(1),pot(1,3)]);assert.equal(r.scores[1],1);assert.equal(r.turn,1);});
test('one-pocket: opponent pot on cue-ball scratch is spotted',()=>{const {r,w}=fixture('onepocket');shoot(r,w,[hit(1),pot(1,3),pot(0)]);assert.equal(r.scores[1],0);assert.ok(w.get(1).active);assert.equal(r.owed[0],1);assert.equal(r.ballInHand,'kitchen');});
test('one-pocket: neutral pocket waits to spot until inning ends',()=>{const {r,w}=fixture('onepocket');shoot(r,w,[hit(1),pot(1,2),pot(2,0)]);assert.deepEqual(r.pendingSpot,[2]);assert.equal(w.get(2).active,false);shoot(r,w,[hit(3),rail(3)]);assert.ok(w.get(2).active);assert.equal(r.pendingSpot.length,0);});
test('one-pocket: foul with no scored ball records a debt',()=>{const {r,w}=fixture('onepocket');shoot(r,w,[]);assert.equal(r.owed[0],1);assert.equal(r.scores[0],0);});
test('one-pocket: a legal pot repays debt before scoring',()=>{const {r,w}=fixture('onepocket');r.owed[0]=1;shoot(r,w,[hit(1),pot(1,2)]);assert.equal(r.owed[0],0);assert.equal(r.scores[0],0);assert.deepEqual(r.pendingSpot,[1]);assert.equal(r.turn,0);});
test('one-pocket: a foul returns a previously scored ball',()=>{const {r,w}=fixture('onepocket');r.scores[0]=1;r.scored[0]=[15];w.get(15).active=false;shoot(r,w,[]);assert.equal(r.scores[0],0);assert.equal(r.owed[0],0);assert.ok(w.get(15).active);});
test('one-pocket: eighth ball wins',()=>{const {r,w}=fixture('onepocket');r.scores[0]=7;shoot(r,w,[hit(1),pot(1,2)]);assert.equal(r.winner,0);});
test('banks: a direct called one-rail bank scores',()=>{const {r,w}=fixture('banks');shoot(r,w,[hit(1),rail(1),pot(1)],{callBall:1,callPocket:2,bankCount:1});assert.equal(r.scores[0],1);});
test('banks: a pocket-jaw brush is not a called bank',()=>{const {r,w}=fixture('banks');shoot(r,w,[hit(1),rail(1,.2,'jaw'),pot(1)],{callBall:1,callPocket:2,bankCount:1});assert.equal(r.scores[0],0);assert.ok(w.get(1).active);});
test('banks: a kick before first contact does not score',()=>{const {r,w}=fixture('banks');shoot(r,w,[rail(0,.05),hit(1),rail(1),pot(1)],{callBall:1,callPocket:2,bankCount:1});assert.equal(r.scores[0],0);});
test('banks: a kiss off another ball does not score',()=>{const {r,w}=fixture('banks');shoot(r,w,[hit(1),rail(1),{type:'ball',a:1,b:2,t:.25},pot(1)],{callBall:1,callPocket:2,bankCount:1});assert.equal(r.scores[0],0);});
test('banks: rail count must match the call',()=>{const {r,w}=fixture('banks');shoot(r,w,[hit(1),rail(1),pot(1)],{callBall:1,callPocket:2,bankCount:2});assert.equal(r.scores[0],0);});
test('3-ball: every stroke counts even with no rail or contact',()=>{const {r,w}=fixture('3ball');shoot(r,w,[]);assert.equal(r.strokes,1);assert.equal(r.turn,0);});
test('3-ball: scratch adds a single penalty stroke',()=>{const {r,w}=fixture('3ball');shoot(r,w,[pot(0)]);assert.equal(r.strokes,2);assert.equal(r.ballInHand,'kitchen');});
test('3-ball: clearing starts the other player on a fresh rack',()=>{const {r,w}=fixture('3ball');shoot(r,w,[hit(1),pot(1),pot(2),pot(3)]);assert.equal(r.scores[0],1);assert.equal(r.turn,1);assert.equal(r.strokes,0);assert.equal(Q.objects(w).length,3);});
test('3-ball: equal final totals produce a draw',()=>{const {r,w}=fixture('3ball');r.target=1;shoot(r,w,[hit(1),pot(1),pot(2),pot(3)]);shoot(r,w,[hit(1),pot(1),pot(2),pot(3)]);assert.equal(r.winner,'draw');});
test('3-ball: lower total wins',()=>{const {r,w}=fixture('3ball');r.target=1;shoot(r,w,[hit(1),pot(1),pot(2),pot(3)]);shoot(r,w,[]);shoot(r,w,[hit(1),pot(1),pot(2),pot(3)]);assert.equal(r.winner,0);});
test('rotation: legal combinations score face values',()=>{const {r,w}=fixture('rotation');shoot(r,w,[hit(1),pot(12),pot(13)]);assert.equal(r.scores[0],25);});
test('rotation: wrong first ball spots the pot without scoring',()=>{const {r,w}=fixture('rotation');shoot(r,w,[hit(2),pot(12)]);assert.equal(r.scores[0],0);assert.ok(w.get(12).active);assert.equal(r.ballInHand,'any');});
test('practice: scratches do not introduce an opponent or penalty',()=>{const {r,w}=fixture('practice');shoot(r,w,[pot(0)]);assert.equal(r.turn,0);assert.equal(r.scores[0],0);assert.equal(r.ballInHand,'any');});
test('rule snapshots are independent, serializable and restorable',()=>{const r=new Q.Rules('onepocket');r.scores[0]=4;r.owed[1]=2;const s=r.snapshot(),copy=Q.Rules.from(s);copy.scores[0]=9;assert.equal(r.scores[0],4);assert.equal(s.scores[0],4);assert.equal(copy.owed[1],2);});
