'use strict';
const t=require('node:test'),a=require('node:assert/strict'),P=require('../src/physics.js'),Q=require('../src/rules.js'),A=require('../src/apa.js'),S=require('../src/settings.js'),M=require('../src/session.js'),C=require('../src/coach.js');
function setup(mode='apa8'){const s=S.normalize(),m=M.create(mode,s,898789),r=M.makeRules(m,['A','B']),w=new P.World(P.rack(mode));return {m,r,w};}
t('strict match validator rejects incomplete or malformed states',()=>{const {m}=setup();for(const key of ['records','lastShot','rackStartStats','lag','seed','settings']){const s=P.clone(m);delete s[key];a.equal(M.valid(s),false,key);}for(const patch of [{seed:-1},{wins:[1]},{settings:{}},{targets:[0,5]},{records:[{}]},{stats:[{},{}]},{lag:{player:3,results:[],awaitNext:false}},{lastShot:{}}])a.equal(M.valid({...m,...patch}),false);});
t('APA 8-ball stalemate voids rack counters and preserves the original breaker',()=>{const {m,r,w}=setup();m.firstBreaker=m.breaker=r.breaker=1;m.stats[0].shots=3;m.stats[1].defense=2;m.innings=2;m.timeouts=[1,1];r.break=false;const nr=M.stalemate(m,w,r);a.equal(nr.turn,1);a.equal(nr.breaker,1);a.deepEqual(m.wins,[0,0]);a.deepEqual(m.stats,[M.stats(),M.stats()]);a.equal(m.innings,0);a.deepEqual(m.timeouts,[0,0]);a.equal(m.records[0].winner,'stalemate');a.equal(m.records[0].innings,0);a.ok(M.valid(m));});
t('APA 9-ball stalemate retains points/innings and marks every remaining ball dead',()=>{const {m,r,w}=setup('apa9');r.break=false;r.scores=[7,6];r.dead=1;r.defense=[1,2];m.innings=4;m.stats[0].shots=6;m.stats[1].defense=2;w.get(1).active=false;w.get(2).active=false;const nr=M.stalemate(m,w,r);a.deepEqual(nr.scores,[7,6]);a.equal(m.innings,4);a.equal(m.stats[0].shots,6);a.equal(m.records[0].dead,9);a.deepEqual(m.records[0].defense,[1,2]);a.equal(m.wins[0],0);a.ok(M.valid(m));});
t('stalemate does not mutate unsupported or finished sessions',()=>{for(const mode of ['8ball','practice']){const {m,r,w}=setup(mode),before=P.clone(m);a.equal(M.stalemate(m,w,r),null);a.deepEqual(m,before);}const {m,r,w}=setup();m.rackEnded=true;a.equal(M.stalemate(m,w,r),null);});
t('next APA rack carries point score, resets timeout count and keeps handicap targets',()=>{const {m,r}=setup('apa9');m.rackEnded=true;m.nextBreaker=1;r.scores=[17,22];m.timeouts=[1,1];m.innings=5;const targets=[...m.targets],nr=M.nextRack(m,r);a.deepEqual(nr.scores,[17,22]);a.deepEqual(m.targets,targets);a.deepEqual(m.timeouts,[0,0]);a.equal(nr.turn,1);a.equal(m.rackStartInnings,5);a.ok(M.valid(m));});
t('a completed match cannot advance another rack',()=>{const {m,r}=setup();m.rackEnded=true;m.winner=0;a.equal(M.nextRack(m,r),null);a.equal(m.rack,1);});
t('timeouts cannot silently leak across racks or bypass Off in practice',()=>{const {m,r}=setup('practice');m.settings.timeouts='off';a.equal(M.useTimeout(m,r),false);m.settings.timeouts='apa';a.equal(M.allowance(m,r),Infinity);M.useTimeout(m,r);a.deepEqual(m.timeouts,[0,0]);});
t('computer selection applies to the configured side, but practice stays human',()=>{const {m,r}=setup();m.settings.opponent='computer';a.equal(M.isComputer(m,r,0),false);a.equal(M.isComputer(m,r,1),true);m.settings.opponent='watch';a.equal(M.isComputer(m,r,0),true);r.mode='practice';a.equal(M.isComputer(m,r),false);});
t('coach direct candidate generator respects 8-ball groups',()=>{const w=new P.World([P.ball(0,.6,.4),P.ball(1,1,.8),P.ball(9,1.5,.4),P.ball(8,1.2,.2)]),r=new Q.Rules('8ball');r.break=false;r.groups=['solids','stripes'];a.deepEqual(C.legalIds(w,r),[1]);a.ok(C.direct(w,r).every(c=>c.ball===1));w.get(1).active=false;a.deepEqual(C.legalIds(w,r),[8]);});
t('coach lowest-first candidate selection respects APA9 rules',()=>{const {r,w}=setup('apa9');r.break=false;w.get(1).active=false;a.deepEqual(C.legalIds(w,r),[2]);a.ok(C.direct(w,r).every(c=>c.ball===2));});
t('no-object coach input is handled without a crash',()=>{const w=new P.World([P.ball(0,.5,.5)]),r=new Q.Rules('practice');a.deepEqual(C.candidates(w,r),[]);a.match(C.solve({world:w.snapshot(),rules:r.snapshot()}).error,/No candidate/);});
t('a recommended easy pot is actually made by the engine and leaves the input untouched',()=>{const w=new P.World([P.ball(0,.8,.45),P.ball(1,1.4,.8)]),r=new Q.Rules('practice');r.break=false;const input={world:w.snapshot(),rules:r.snapshot(),depth:'quick',skill:4,context:{variation:false,miscues:false,chalk:false,skill:4,condition:1,radius:P.R,mass:P.M,cfg:w.cfg}},before=P.clone(input),out=C.solve(input);a.ok(out.candidates?.some(c=>c.measure.legal&&c.measure.actual));a.deepEqual(input,before);const chosen=out.candidates.find(c=>c.measure.actual),demo=C.demonstration(input,chosen);a.ok(demo.settled);a.ok(demo.events.some(e=>e.type==='pocket'&&e.id===chosen.ball&&e.pocket===chosen.pocket));a.deepEqual(input,before);a.equal(w.atRest(),true);});
t('coach scratch evaluation rejects a false easy win',()=>{const w=new P.World([P.ball(0,1.0,P.W/2),P.ball(1,1.5,.8)]),r=new Q.Rules('9ball');r.break=false;r.ballInHand=null;const m=C.measure(w,r,{ball:1,pocket:1,angle:Math.PI/2,power:60,side:0,up:0,elevation:0,bankCount:1,safety:false},{miscues:false});a.ok(!m||!m.legal);});
t('lag search uses actual simulation and returns a finite playable power',()=>{const w=new P.World([P.ball(0,P.L/4,P.W/4)]),result=C.lag({world:w.snapshot()});a.ok(result.power>=20&&result.power<=60);a.ok(Number.isFinite(result.distance));const copy=P.World.from(w.snapshot());copy.strike(0,0,0,0,result.power,{noMiscue:true});a.ok(copy.simulate(30).settled);a.ok(copy.events.some(e=>e.type==='rail'&&copy.table.rails[e.rail].a[0]===P.L));a.ok(copy.get(0).p[0]<.3);});
